WebApplication2/Models/Services.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class Services
    {
        public int Id { get; set; }
        [NotMapped]
        [DisplayName("Upload File")]
        public IFormFile image { get; set; }

        public string file { get; set; }
        public string link { get; set; }
        public string smallDesc { get; set; }
  
        public string largDesc { get; set; }
        public string title { get; set; }
        public string tag { get; set; }
        public string status { get; set; }
        public bool trash { get; set; }
        public DateTime created_at { get; set; }
        public DateTime updated_at { get; set; }
        public string Catogry { get; set; }

    }
}

WebApplication2/Models/ServicesViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class ServicesViewModel
    {
         [Required(ErrorMessage = "Please enter first name")]  
        [Display(Name = "First Name")]  
        public string link { get; set; }  
  
        [Required(ErrorMessage = "Please enter last name")]  
        [Display(Name = "First Name")]  
        public string smallDesc { get; set; }  
  
        [Required(ErrorMessage = "Please enter age")]  
        public int largDesc { get; set; }  
  
        [Required(ErrorMessage = "Please choose gender")]  
        public string title { get; set; }  
  
        [Required(ErrorMessage = "Please enter position")]  
        public string tag { get; set; }  
  
        [Required(ErrorMessage = "Please enter office")]  
        public string Catogry { get; set; }  
  
 
  
        [Required(ErrorMessage = "Please choose profile image")]  
        [Display(Name = "Service Picture")]  
        public IFormFile image { get; set; }

        [Required(ErrorMessage = "Please choose profile file")]
        [Display(Name = "Service File")]
        public IFormFile file { get; set; }
    }
}

WebApplication2/Controllers/Backend/ServicesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data;
using static WebApplication2.Constants.Permissions;

namespace WebApplication2.Controllers.Backend
{
    [Authorize(Roles = "SuperAdmin")]

    public class ServicesController : Controller
    {

        private readonly ApplicationDbContext _context;
        public ServicesController(ApplicationDbContext context)
        {
            _context = context;
        }



        public async Task<IActionResult> Index()
        {
            var service = await _context.Services.ToListAsync();
            return View(service);
        }

        //AddOrEdit Get Method
        public async Task<IActionResult> create(int? Id)
        {
     
            return View();

        }

        //AddOrEdit Post Method
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> create([Bind("Id,image,file,link,smallDesc,largDesc,title,tag,status,trash,Catogry,updated_at,created_at")]
Models.Services servicesdata)
        {
            _context.Services.Add(servicesdata);
            _context.SaveChanges();
            var service = await _context.Services.ToListAsync();
            return View("/Views/Services/Index.cshtml", service);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([Bind("Id,image,file,link,smallDesc,largDesc,title,tag,status,trash,Catogry,updated_at,created_at")]
Models.Services servicesdata)
        {
            _context.Services.Update(servicesdata);
            _context.SaveChanges();
            return View("Views/backend/Services/Index");
        }


        
        public async Task<IActionResult> Update(int Id)
        {

            var serc = await _context.Services.FirstOrDefaultAsync(m => m.Id == Id);


            return View(serc);

        }
        public async Task<IActionResult> Details(int Id)
        {

            var serc = await _context.Services.FirstOrDefaultAsync(m => m.Id == Id);


            return View(serc); 

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int Id)
        {
            var services = await _context.Services.FindAsync(Id);

            _context.Services.Remove(services);
            _context.SaveChanges();
            var servicaaae = await _context.Services.ToListAsync();

            return View("/Views/Services/Index.cshtml", servicaaae);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateProfile(int Id, [Bind("Id,image,file,link,smallDesc,largDesc,title,tag,status,trash,Catogry,updated_at,created_at")]
Models.Services servicesdata)
        {


            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(servicesdata);
                    await _context.SaveChangesAsync();

                }
                catch (DbUpdateConcurrencyException)
                {

                    throw;
                }
                var servicess = await _context.Services.ToListAsync();

                return View("/Views/Services/Index.cshtml", servicess);

                return Redirect("~/Services/Index");


            }
            var service = await _context.Services.ToListAsync();
                                    return Redirect("~/Services/Index");

 

        }
    }
}

WebApplication2/Views/Services/Details.cshtml
@model WebApplication2.Models.Services
@{
    ViewData["Title"] = "CMS Page";
    Layout = "~/Views/backend/layout.cshtml";

}

 
<div class="container">
    <div class="justify-content-center">
     
        <div class="card">
            <div class="card-header">
                Service
            
                <span class="float-right">
                    @*<a class="btn amanbt" href="Index">Back</a>*@
                </span>
              
            </div>
            <div class="card-body">


                <strong>Title:</strong>
                <div class="jumbotron py-3 ">
                  @Model.title
                </div>


                <strong>Small Description:</strong>
                <div class="jumbotron py-3">
                    @Model.smallDesc
                </div>

                <strong>large Description:</strong>
                <div class="jumbotron py-3">
                    @Model.largDesc
                </div>

                <strong>Tag:</strong>
                <div class="jumbotron py-3">
                    @Model.tag
                </div>

                <strong>Category:</strong>
                <div class="jumbotron py-3">

                    @Model.Catogry
                </div>

                <strong>Video:</strong>
                <div class="jumbotron py-3">
                    @Model.link
                </div>
                <div class="row text-center">
                    <div class="col-lg-6">

                        <label>Image:</label>
                        <div class="py-3 ">
                            @Model.image
                        </div>
                    </div>

                    <div class="col-lg-6">

                        <strong>file:</strong>
                        <div class="py-3 mt-4">
                            @Model.file
                        </div>


                    </div>



                </div>




            </div>
        </div>
    </div>
</div>
 

WebApplication2/Views/Services/Index.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
@{
    ViewData["Title"] = "CMS Page";
    Layout = "~/Views/backend/layout.cshtml";
    var i = 0;

}




@using WebApplication2.Constants
@model IEnumerable<WebApplication2.Models.Services>



<div class="container">
    <br />

    <div style="width:auto; margin:0 auto;">
        <div class="card-header">
            Services
            <span class="float-right">
                <a class="btn amanbt" href="~/Services/create">New Service</a>
            </span>
        </div>
        <div class="table-responsive">

            <table class="table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>title</th>
                      
                        <th>Action</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)

                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.title)
                            </td>
                            
                            <td>

                                @*@if ((AuthorizationService.AuthorizeAsync(User, Permissions.Services.Create)).Result.Succeeded)
        {*@

                                @*}*@

                                @*@if ((AuthorizationService.AuthorizeAsync(User, Permissions.Services.View)).Result.Succeeded)
        {*@
                                <a asp-action="Details" class="btn btn-warning" asp-route-Id="@item.Id">Details</a>

                                @*//}*@

                                @*@if ((AuthorizationService.AuthorizeAsync(User, Permissions.Services.Edit)).Result.Succeeded)
        {*@

                                <a asp-action="Update" class="btn btn-warning" asp-route-Id="@item.Id">Modify</a>
                                @*}*@
                                @*@if ((AuthorizationService.AuthorizeAsync(User, Permissions.Services.Delete)).Result.Succeeded)
        {*@
                          


                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal_@item.Id">
                                   Delete
                                </button>

                                <!-- Modal -->
                                <div class="modal fade" id="exampleModal_@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Do you want to Delete @item.title?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <form asp-action="Delete" asp-route-Id=@item.Id>
                                                    <input class="btn btn-primary" type="submit" value="Save" />
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                @*}*@






                            </td>

                        </tr>

                    }
                </thead>
            </table>
        </div>
        </div>


                </tbody>
            </table>
            </div>











        @*@if ((AuthorizationService.AuthorizeAsync(User, Permissions.Services.Create)).Result.Succeeded)
                    {
                    <button class="btn btn-success">Create</button>
                    }
                    @if ((AuthorizationService.AuthorizeAsync(User, Permissions.Services.View)).Result.Succeeded)
                    {
                        <button class="btn btn-info">View</button>
                    }
                    @if ((AuthorizationService.AuthorizeAsync(User, Permissions.Services.Edit)).Result.Succeeded)
                    {
                        <button class="btn btn-warning">Modify</button>
                    }
                    @if ((AuthorizationService.AuthorizeAsync(User, Permissions.Services.Delete)).Result.Succeeded)
                    {
                        <button class="btn btn-danger">Delete</button>
                    }*@

WebApplication2/Views/Services/Update.cshtml
@model WebApplication2.Models.Services
@{
    ViewData["Title"] = "CMS Page";
    Layout = "~/Views/backend/layout.cshtml";

}


<div class="content-wrapper">
    <div class="container">
        <div class="justify-content-center">
            <div class="card">
                <div class="card-header">
                    Create Service
                    <span class="float-right">
                        <a class="btn amanbt" href="Index">SERVICES</a>
                    </span>
                </div>
                <div class="card-body">
                    <div class="container">
 
                            <form asp-controller="Services" asp-action="Update" >
                                <input name="_token" type="hidden" value="zDSlVPilwm5WnSIE7YOU1JOcZCjlHYS7EXfpVcf3">
                                <div class="row">
                                    <div class="col-lg-6">

                                        <div class="row mt-3 mr-2">

                                            <label class="control-label"><strong>Service Title:</strong></label>
                                            <input name="title" class="form-control"  value="@Model.title"/>

                                        </div>





                                        <div class="row mt-3 mr-2">


                                            <label class="control-label"><strong>Service Small Description:</strong></label>
                                            <textarea name="smallDesc" value="@Model.smallDesc" class="form-control" maxlength="90" cols="50"></textarea>


                                        </div>
                                        <div class="row mt-3 mr-2">

                                            <label class="control-label"><strong>Service Tag:</strong></label>
                                            <input name="tag" value="@Model.tag" class="form-control" />
                                        </div>

                                        <div class="row mt-3 mr-2">

                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="row mt-3">

                                            <label class="control-label"><strong>Service Image:</strong></label>
                                            <input name="image" value="@Model.image" class="form-control" />

                                        </div>

                                        <div class="row mt-3">
                                            <label class="control-label"><strong>Service File:</strong></label>
                                            <input class="form-control" value="@Model.file"  name="file" />
                                        </div>
                                        <br />


                                        <div id="div11" class="row mt-3">
                                            <strong>Service Category:</strong>


                                            <input class="form-control"  value="@Model.Catogry"  name="Catogry" />



                                            <div class="row mt-4">
                                                <label class="control-label"><strong>Service Video Link:</strong></label>
                                                <input name="link" value="@Model.link"  class="form-control" />
                                            </div>
                                        </div>

                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12 py-3">
                                            <label class="control-label"><strong>Service Large Description:</strong></label>
                                            <textarea name="largDesc" value="@Model.largDesc"  class="form-control" id="summary-ckeditor" cols="50" rows="10"></textarea>


                                        </div>
                                    </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn btn-success px-4 py-3">Submit</button>
                                    </div>
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

WebApplication2/Views/Services/create.cshtml
 @model WebApplication2.Models.ServicesViewModel
@{
    ViewData["Title"] = "CMS Page";
    Layout = "~/Views/backend/layout.cshtml";

}


<div class="content-wrapper">
    <div class="container">
        <div class="justify-content-center">
            <div class="card">
                <div class="card-header">
                    Create Service
                    <span class="float-right">
                        <a class="btn amanbt" href="Index">SERVICES</a>
                    </span>
                </div>
                <div class="card-body">
                    <div class="container">
                        <form asp-controller="Services" asp-action="create">
                            <input name="_token" type="hidden" value="zDSlVPilwm5WnSIE7YOU1JOcZCjlHYS7EXfpVcf3">
                            <div class="row">
                                <div class="col-lg-6">

                                    <div class="row mt-3 mr-2">

                                        <label class="control-label"><strong>Service Title:</strong></label>
                                        <input name="title" class="form-control" />

                                    </div>





                                    <div class="row mt-3 mr-2">

                                        <label class="control-label"><strong>Service Small Description:</strong></label>
                                        <textarea name="smallDesc" class="form-control" maxlength="90" cols="50"></textarea>


                                    </div>
                                    <div class="row mt-3 mr-2">

                                        <label class="control-label"><strong>Service Tag:</strong></label>
                                        <input name="tag" class="form-control" />
                                    </div>

                                    <div class="row mt-3 mr-2">

                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="row mt-3">

                                        <label asp-for="image" class="control-label"></label>
                                        <div class="custom-file">
                                            <input asp-for="image" accept="image/*" />
                                            <label class="custom-file-label" for="customFile">Choose file</label>



                                        </div>

                                        <div class="row mt-3">
                                            <label class="control-label"><strong>Service File:</strong></label>
                                            <input class="form-control" type="file" name="filefile" />

                                        </div>
                                        <br />


                                        <div id="div11" class="row mt-3">
                                            <strong>Service Category:</strong>


                                            <input class="form-control" name="Catogry" />



                                            <div class="row mt-4">
                                                <label class="control-label"><strong>Service Video Link:</strong></label>
                                                <input name="link" class="form-control" />
                                            </div>
                                        </div>

                                    </div>
                                <div class="row">
                                    <div class="col-lg-12 py-3">
                                        <label class="control-label"><strong>Service Large Description:</strong></label>
                                        <textarea name="largDesc" class="form-control" id="summary-ckeditor" cols="50" rows="10"></textarea>


                                    </div>
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success px-4 py-3">Submit</button>
                                </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>